### ISSUE TITLE
"Title" from "Modals" doesn't change

### ISSUE THREAD

**Issue by manel00** [ionic-team/capacitor-site#108]
https://capacitorjs.com/docs/apis/modals#type-162647

I set up an alert and confirm prompt, and the titles, if i put whatever, always showing "ALERT" or "CONFIRM" text! It doesn't use the string i'm putting there, it should be fixed

**Comment by Ionitron** [comment]
This issue doesn't appear to be an issue with the Capacitor site or documentation. Please [use this form](https://github.com/ionic-team/capacitor/issues/new/choose) to refile your issue elsewhere.

Thanks!
Ionitron 💙
