### ISSUE TITLE
feat: add Electron to docs

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-site#109]
### Description

I believe a section to the documentation for Capacitor JS should be added to explain how to get setup with the Electron platform as I can't seem to find anything listed here: https://capacitorjs.com/docs/web

### Platform(s)

Electron

### Preferred Solution

I think a new section should be added

**Comment by dwieeb** [comment]
We won't be doing this because Electron will be a community platform for Capacitor 3+. See https://github.com/capacitor-community/electron

We may, however, create a page for community platforms or have tutorials for the community electron platform in the future.
