### ISSUE TITLE
Script tags not escaped

### ISSUE THREAD

**Issue by tricki** [ionic-team/capacitor-site#114]
Some example script tags are not properly escaped and therefore invisible to the user (and are actually loaded).

1. On the ["PWA Elements" page](https://capacitorjs.com/docs/pwa-elements#including-through-script-tag)
2. On the [web docs](https://capacitorjs.com/docs/web#using-capacitor-as-a-script-include)

**Comment by dwieeb** [comment]
This appears to be working now.
