### ISSUE TITLE
Modals doesn't work on Ionic 5.3.X

### ISSUE THREAD

**Issue by manel00** [ionic-team/capacitor-site#116]
Hello,

Trying to show through PWA on Android/iOS and cannot see anything, neither on web

Thank you

**Comment by Ionitron** [comment]
This issue doesn't appear to be an issue with the Capacitor site or documentation. Consider [refiling your issue](https://github.com/ionic-team/capacitor/issues/new/choose) in a better place. For support questions, please see our [Support Page](https://ionicframework.com/support).

Thanks!
Ionitron 💙
