### ISSUE TITLE
Uncaught (in promise): Error: location unavailable Error: location unavailable

### ISSUE THREAD

**Issue by AhmedHammouda** [ionic-team/capacitor-site#118]
Hi,

I'm using ionic capacitor with MapBox in order to get my current location

i followed the documentation in "https://capacitorjs.com/docs/apis/geolocation"

everything work fine when i run my project with "ionic serve" ( i get my location in the map and there is no errors in browser console ) 

![browser ](https://user-images.githubusercontent.com/36247078/92959812-65337700-f464-11ea-9656-847665429ab2.png)

BUT, when i tried to run it on simulator i'm getting a blank page.
those are the steps that i did :
1/ add the map and test it  without geolocation code (work fine )
2/ add code of geolocation ( get a blank page )
3/ i run my project using :  "ionic build" , "npx cap sync", "ionic cap open android"

1/ package.json :
"dependencies": {
    "@angular/common": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/pwa": "^0.803.23",
    "@angular/router": "^8.2.14",
    "@angular/service-worker": "^8.2.14",
    "@capacitor/android": "^2.4.0",
    "@capacitor/core": "2.4.0",
    "@ionic-native/core": "5.0.0-beta.15",
    "@ionic-native/geolocation": "^5.27.0",
    "@ionic-native/in-app-browser": "5.0.0-beta.15",
    "@ionic-native/splash-screen": "5.0.0-beta.15",
    "@ionic-native/status-bar": "5.0.0-beta.15",
    "@ionic/angular": "^5.1.1",
    "@ionic/storage": "^2.1.3",
    "cordova-android": "^8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "^3.6.4",
    "mapbox-gl": "^1.11.1",
    "rxjs": "^6.5.4",
    "sw-toolbox": "3.6.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.23",
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular-devkit/core": "^8.3.23",
    "@angular-devkit/schematics": "^8.3.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@capacitor/cli": "2.4.0",
    "@ionic/angular-toolkit": "^2.1.2",
    "@ionic/lab": "^2.0.19",
    "@types/jasmine": "3.4.6",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "^12.12.26",
    "codelyzer": "^5.2.1",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "^5.4.3",
    "puppeteer": "^1.20.0",
    "ts-node": "8.5.0",
    "tslint": "^5.20.1",
    "typescript": "~3.5.3"
  },
  "cordova": {
    "platforms": [
      "ios",
      "android"
    ],
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-firebase": {}
    }
  }
}

2/ screenchot of the page before adding the geolocation code :
![before](https://user-images.githubusercontent.com/36247078/92959889-8dbb7100-f464-11ea-88cc-0c0da4dd27f5.png)

3/ screenshot of the page after adding the geolocation code with AndroidManifest.xml in android studio :
![after adding](https://user-images.githubusercontent.com/36247078/92959947-a4fa5e80-f464-11ea-8f62-8d5a78f07511.png)

![pop up](https://user-images.githubusercontent.com/36247078/92959972-b0e62080-f464-11ea-89aa-1639a26bf640.png)

4/ screenshot of my code :
![mycode](https://user-images.githubusercontent.com/36247078/92959991-b93e5b80-f464-11ea-9947-ba98f414c5f7.png)

5/ sreencshot of the error i get when i debug my app :
![debug](https://user-images.githubusercontent.com/36247078/92960013-c1969680-f464-11ea-9b01-f4bce9e0998a.png)

**Comment by Ionitron** [comment]
This issue doesn't appear to be an issue with the Capacitor site or documentation. Please [use this form](https://github.com/ionic-team/capacitor/issues/new/choose) to refile your issue elsewhere.

Thanks!
Ionitron 💙
