### ISSUE TITLE
Improve live reload docs

### ISSUE THREAD

**Issue by jupl** [ionic-team/capacitor-site#12]
I am interested in using this for a React project. I am a fan of leveraging hot reloading with a dev server and am trying to figure out how to point to my assets served up in a dev server in development when targeting Android and iOS. AFAIK the only thing I can do is point to files in webDir and nothing else.

**Comment by dotNetkow** [comment]
Hey all! We just created a new [Live Reload guide](https://capacitorjs.com/docs/guides/live-reload) that should help with all of these questions. cheers!
