### ISSUE TITLE
feat: Permission plugin is missing example

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/capacitor-site#123]
### Description

On https://capacitorjs.com/docs/apis/permissions there is no example of how to use this plugin

I've tried 
```
const hasPermission = await Permissions.query(PermissionsOptions.Camera);
```
and
```
const hasPermission = await Permissions.query('Camera');
```
But none worked. An example would help.

### Preferred Solution

A minimal example on how to use the plugin

**Comment by sufita** [comment]
Please try this `const hasPermission = await Permissions.query({ name: 'camera' });`

**Comment by basvdijk** [comment]
@sufita thanks for your reply. VScode gives that 'name' is not a PermissionType

![image](https://user-images.githubusercontent.com/644550/94710186-d4efa000-0346-11eb-8375-4a8218e1df72.png)

**Comment by sufita** [comment]
Do you use typescript ? 
How about this 
```
import { Plugins, PermissionType } from '@capacitor/core';
const { Permissions } = Plugins;

const hasPermission = await Permissions.query({
                                        name: PermissionType.Camera
                                       });


```

**Comment by basvdijk** [comment]
> Do you use typescript ?
> How about this ?
> 
> ```
> import { Plugins, PermissionType } from '@capacitor/core';
> const { Permissions } = Plugins;
> 
> const hasPermission = await Permissions.query({ name: PermissionType.Camera });
> ```

@sufita Thank for thinking with me :) Tried that as well gave an error. I tried all kinds of combinations, strings, types, within an object, without, all seem to fail. Therefore my request for an example. I've even tried to digest the sourcecode in order to understand why it wasn't working. Without success...

**Comment by sufita** [comment]
Maybe it's because of the typescript version.
Try to change your typescript version by clicking on right side of the bottom of VScode.
Click select, and choose the lower version.

**Comment by raykin** [comment]
Encounter same requirement.
```typescript
    const permission = await Permissions.query({ name: PermissionType.Geolocation });
```
works in Emacs.

**Comment by jcesarmobile** [comment]
Closing as Permissions plugin was removed in Capacitor 3, now every plugin that requires permissions can have methods for checking and requesting permissions easily.

**Comment by wellwoller** [comment]
> Closing as Permissions plugin was removed in Capacitor 3, now every plugin that requires permissions can have methods for checking and requesting permissions easily.

How useful is a geolocation permissions request if I have no way of requesting to turn on geolocation services? Could you give us a simple solution to turn that on on the geolocation plugin?
