### ISSUE TITLE
Scroll issue with link fragments/anchors

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-site#133]
Opening a fragment link (like https://capacitor-site-git-initial-v3-updates.ionic1.vercel.app/docs/v3/android#opening-the-android-project) doesn't scroll enough:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/236501/96310944-38233880-0fbd-11eb-8eef-f68ef472fa95.png">

I would expect something like this:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/236501/96310913-2b9ee000-0fbd-11eb-8b15-1d80cf69fa8f.png">

**Comment by jaredcbaum** [comment]
Fixed: [see here](https://capacitorjs.com/docs/v3/android#opening-the-android-project)
