### ISSUE TITLE
Clicking on fragment link doesn't scroll to correct spot

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-site#134]
Click the "Learn more about `sync`" fragment link in [this page](https://capacitor-site-git-initial-v3-updates.ionic1.vercel.app/docs/v3/android#adding-the-android-platform).

Notice it scrolls incorrectly to some random spot:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/236501/96311156-b253bd00-0fbd-11eb-8ced-37e2a9be83c4.png">

I would expect it to scroll to the correct anchor:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/236501/96311172-bd0e5200-0fbd-11eb-8252-7cace82f2e45.png">

**Comment by jaredcbaum** [comment]
Fixed in latest site version.
