### ISSUE TITLE
No CSS for em

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-site#136]
`<em>` isn't styled. See [this page](https://capacitorjs.com/docs) with "iOS, Android, and the web". The "and" is supposed to be emphasized/italicized

**Comment by jaredcbaum** [comment]
For me it's showing "font-style: italic" and shows up italicized

**Comment by dwieeb** [comment]
That's because it's using the default stylesheet of Chrome. We're not giving it a style in our CSS. It doesn't work in Firefox.

**Comment by jaredcbaum** [comment]
Gotcha.  Im working on a revamped version of the capacitor site and it will be included in the site-wide styles.

**Comment by jaredcbaum** [comment]
docs em styles added in latest
