### ISSUE TITLE
Colors are incorrectly documented

### ISSUE THREAD

**Issue by aparajita** [ionic-team/capacitor-site#138]
Currently, colors are documented like this:

> Possible values for backgroundColor in your capacitor.config.json are either #RGB or #ARGB.

That is incorrect. Colors are actually either #RGB or #RGBA, and the # is optional. I suggest using this language, as it is explicit and covers all valid syntax:

> Possible values for backgroundColor in your capacitor.config.json are either #RGB (six case-insensitive hex digits) or RGBA (eight case-insensitive hex digits). In both cases the leading "#" is optional.

**Comment by aparajita** [comment]
I'm closing this, because the actual problem is that on iOS the color is parsed incorrectly.

**Comment by aparajita** [comment]
So it turns out that on iOS colors are parsed as RGBA, which is the way it **should** be, because that is the [standard in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba()).

Unfortunately, on Android Capacitor is reading colors as ARGB. So the real problem is color parsing on Android.

**Comment by jcesarmobile** [comment]
on Capacitor 3 both iOS and android colors are parsed as RGBA and docs have been updated

**Comment by aparajita** [comment]
Super, thank you!
