### ISSUE TITLE
Function type is being documented

### ISSUE THREAD

**Issue by aparajita** [ionic-team/capacitor-site#139]
Your documentation generator is generating documentation for `Function` when that is the type of a parameter. That is quite unnecessary, as we know what a Function is. Perhaps there's a way to exclude that from the generator.

**Comment by dwieeb** [comment]
Can you send a link?

**Comment by aparajita** [comment]
https://capacitorjs.com/docs/apis/splash-screen#function

**Comment by dwieeb** [comment]
The documentation generator is just reading the types in this case: https://github.com/ionic-team/capacitor/blob/2.x/core/src/core-plugin-definitions.ts#L1747-L1756

We aren't using the `Function` type in Capacitor 3. Truthfully I don't even know what that callback is for. You can follow this issue for when we work on splitting out the Splash Screen plugin: https://github.com/ionic-team/capacitor/issues/3227

**Comment by aparajita** [comment]
I know it's just reading the types, and I also know the callback will go away. 😁 Just in case that appears elsewhere I thought I'd bring it up.

I have a way better version of the SplashScreen plugin I'm working on, I'll submit a PR when it's done.
