### ISSUE TITLE
Clarification: Android `success` or `resolve`?

### ISSUE THREAD

**Issue by Kikketer** [ionic-team/capacitor-site#14]
Looking at the docs for Android plugins and I see a call for `success` and `resolve` but I'm not sure if they are interchangeable or if they serve different purposes.

https://capacitor.ionicframework.com/docs/plugins/android

Just a documentation update, I'd be willing to do a PR on it but I'm not sure what to say.

**Comment by joewoodhouse** [comment]
The custom plugin guide docs also reference both .success and .resolve, which is a bit confusing:
https://capacitorjs.com/docs/plugins/android

**Comment by dwieeb** [comment]
`.success` and `.error` are [going to be deprecated](https://github.com/ionic-team/capacitor/commit/40b6fe533386e49273eacad8b1c29f6b5f0a7f99) in Capacitor 3, so use `.resolve` and `.reject`. We'll update the site examples to use the preferred methods.

**Comment by dwieeb** [comment]
This is done in the v3 docs: https://capacitorjs.com/docs/v3
