### ISSUE TITLE
The description is different from the content.

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/capacitor-site#146]
These description is not explain plugin.

> Step-by-step guides to setting up your system and installing the framework.
> Dive into Ionic Framework’s beautifylly designed UI component library.

<img width="804" alt="スクリーンショット 2020-10-24 9 57 55" src="https://user-images.githubusercontent.com/9690024/97064333-18ed6200-15e0-11eb-8f46-55ecc7a7d9ac.png">

**Comment by dwieeb** [comment]
Thank you @rdlabo!
