### ISSUE TITLE
[Docs] site is not mobile friendly

### ISSUE THREAD

**Issue by stewwan** [ionic-team/capacitor-site#15]
![Screen Shot 2019-03-15 at 13 55 00](https://user-images.githubusercontent.com/719763/54448361-4b5b8b80-472a-11e9-96c9-15148ab819ff.png)

**Comment by jaredcbaum** [comment]
Working well as of latest.  Checked on smallest iphone size (5/SE).  Content wraps and code examples/tables are horizontally scroll-able.
