### ISSUE TITLE
Admonitions

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor-site#152]
Implement admonitions (aka callouts) for the docs:

```html
<aside class="info">Example text **with markdown**.</aside>
<aside class="warning">Example text **with markdown**.</aside>
```

example of info: https://docs.djangoproject.com/en/3.1/topics/http/urls/#passing-extra-options-to-view-functions
example of warning: https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/

**Comment by jcesarmobile** [comment]
the docs are now showing :::info, :::warning and :::note that format the text inside in a different way, not sure if that's what you wanted, but looks similar, so I'm going to close
