### ISSUE TITLE
Camera Plugin - Width/Height not enforced (working)

### ISSUE THREAD

**Issue by wcooperscott** [ionic-team/capacitor-site#163]
`ionic capacitor -v        6.11.0`

Setting width and height with (or without) `preserveAspectRatio` does not change the projected outcome.

```
const image = await Camera.getPhoto({
        quality: 90,
        allowEditing: false,
        width: 320,
        height: 320,
        preserveAspectRatio: true,
        direction: CameraDirection.Rear,
        resultType: CameraResultType.Base64,
        source
      });
```

**Comment by jcesarmobile** [comment]
Please, report capacitor issues on capacitor repository and provide all the requested information https://github.com/ionic-team/capacitor/issues
