### ISSUE TITLE
bug: Cannot copy code examples in documentation when using Firefox

### ISSUE THREAD

**Issue by jaydrogers** [ionic-team/capacitor-site#169]
Hi all,

Thanks for making such a great product! I ran into a minor bug that I wanted to make you aware of.

### Problem
* I cannot copy code when using Firefox on macOS

### Steps to replicate
1. Go to https://capacitorjs.com/docs/apis/browser
2. Go into a code block and try to select and copy the code examples

![Screen Shot 2020-11-09 at 12 26 36 PM](https://user-images.githubusercontent.com/3174134/98581566-4d6f4800-2287-11eb-8d21-1bf6c26e2496.png)

### Expected Results
* I should be able to select and copy the code

### Environment
You can find my environment here: https://www.whatsmybrowser.org/b/NHKT9

### Workaround
1. Scroll down to the bottom of the page
2. Click `Contribute`
3. Copy the code from Github

Anyone else able to replicate this?

**Comment by dwieeb** [comment]
I also have this problem.

**Comment by pwespi** [comment]
Same with Firefox on Windows.

My browser environment: https://www.whatsmybrowser.org/b/3VEOQ (nice site by the way 👍  ).

**Comment by pwespi** [comment]
Actually I found out that code examples are selectable in Firefox (you can also copy it). But it's not visible because the selection color is the same as the background. I submitted a PR to fix it.
https://github.com/ionic-team/capacitor-site/pull/178

**Comment by jaydrogers** [comment]
Thanks for the fix @pwespi!

**Comment by jaredcbaum** [comment]
Thanks @jaydrogers for the detailed bug report as well! 💪
