### ISSUE TITLE
feat: documenting local web/pwa plugin

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/capacitor-site#175]
The "Creating Plugins" portion of the Capacitor Plugins documentation contains information on how to implement the Web/PWA portion of a plugin when generated using the Plugin generator: `npx @capacitor/cli plugin:generate`.

It is not clear how one would go about this process when writing local custom code. 

In addition, it would be beneficial to document the local custom code equivalent of the Creating Plugins > Development Workflow portion of the Capacitor Plugins documentation so developers can learn how to type the local plugin being worked on in order to establish a contract all platforms can adhere to.

**Comment by jcesarmobile** [comment]
Guides now include that information:

https://capacitorjs.com/docs/ios/custom-code#javascript
https://capacitorjs.com/docs/android/custom-code#javascript
