### ISSUE TITLE
Documentation on Capacitor plugin help missing a common scenario

### ISSUE THREAD

**Issue by tylerclark** [ionic-team/capacitor-site#184]
On this page: https://capacitorjs.com/docs/plugins/workflow

There is no mention of symbolic linking issues when `npm link` doesn't work right. Sometimes you need to run the server locally as `npm run serve  --preserve-symlinks` for things to resolve locally. I fought this issue here:
https://forum.ionicframework.com/t/capacitor-local-plugin-support-not-working/201475/2

It seems pretty common when I did some Google searching so perhaps this should be mentioned for those running into the same issue.

**Comment by jcesarmobile** [comment]
that guide no longer uses npm link, instead it uses npm install with path to the local package, this way you don't have those kind of problems npm link presents
