### ISSUE TITLE
Cap 3 upgrade guide: Ionic Framework plugin usage

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/capacitor-site#216]
In the upgrade guide, under the [migrating your app section](https://capacitorjs.com/docs/v3/updating/3-0#migrating-your-app-to-use-the-new-official-plugin-packages), there's this mention:

_The Ionic Framework makes use of APIs in the following plugins:

App
Haptics
Keyboard

For best performance with Ionic Framework, you should make sure these plugins are installed even if you don’t import them in your app: [install details]_

Questions to document/expand upon:
- Are these three required? If not, what are you missing out on?
- Cap 3 is all about better performance (for example, lower bundles since core plugins are split into separate packages). If I include these, how much does my app size increase?

**Comment by bartvanraaij** [comment]
Related: https://github.com/ionic-team/capacitor-site/pull/260

As per my experience:

- Without `StatusBar` the "Tap statusbar to scroll to top"-feature on iOS doesn't work
- Without `SplashScreen` the splash screen doesn't show

I'm not sure about App, Haptics and Keyboard but I presume that stuff like swipes and viewport-resizes don't work as expected without them.
So I think the wording "performance" should be changed to something along the lines of "expected native-like behaviour".
