### ISSUE TITLE
Document variables removed from variables.gradle

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-site#221]
Some variables were removed from the app template's `variables.gradle` because they were specific to plugins: https://github.com/ionic-team/capacitor/pull/4093/files

In the upgrade guide, document that people can remove certain variables.

PR that added them to plugin documentation: https://github.com/ionic-team/capacitor-plugins/pull/204

**Comment by jcesarmobile** [comment]
was done as part of https://github.com/ionic-team/capacitor-site/pull/234
