### ISSUE TITLE
Links in upgrade docs aren't working

### ISSUE THREAD

**Issue by skotturi** [ionic-team/capacitor-site#246]
The links in the android section don't link properly do the plugin #variables section. 

I checked the source code and the links are correct but when you click them, they append an addition /v3/ in the path. 

To repro, click any of these links:
![image](https://user-images.githubusercontent.com/4960284/111041503-50bd4080-83ed-11eb-8606-48f59a626d8d.png)

Instead of going to the correct page, this happens:

![image](https://user-images.githubusercontent.com/4960284/111041523-629ee380-83ed-11eb-9665-094973844cc8.png)

The links in the readme source are correct:
![image](https://user-images.githubusercontent.com/4960284/111041567-9bd75380-83ed-11eb-8858-fd43ed301f65.png)

https://github.com/ionic-team/capacitor-site/blob/main/pages/docs/v3/updating/3-0.md

But instead they get routed to: https://capacitorjs.com/docs/v3/v3/apis/browser

Simply removing the duplicate v3 in the path renders the page correctly

**Comment by jcesarmobile** [comment]
now that v3 docs are the main ones it's no longer an issue, closing
