### ISSUE TITLE
Clicking next or back links collapses sidemenu section 

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-site#25]
1. Go to a page in the middle of a section, e.g. Basics -> Running Your App
1. "Basics" sidemenu section is open
1. Click Back or Next at the bottom of the page
1. "Basics" sidemenu section is collapsed

**Comment by mlynch** [comment]
This is actually a bigger issue which is fresh navigation to a page in any of the other sections doesn't auto open

**Comment by mlynch** [comment]
Fixed
