### ISSUE TITLE
Capacitor site IP is blacklisted by a security tool called "GreenSnow", can't access docs

### ISSUE THREAD

**Issue by jasonwatkins** [ionic-team/capacitor-site#296]
Hi,

I was trying to access the capacitor documentation today at https://capacitorjs.com, and discovered it is being blocked by our network because the IP address appears on a blacklist.

https://blocklist.greensnow.co/greensnow.txt 

Just wanted to let you know, as there may be others behind corporate firewalls running into the same issue. I know this presents as a "my network" issue, but something triggered the IP to be added to the blacklist. 

Thanks for all the work you have been doing to move the framework forward!

**Comment by jcesarmobile** [comment]
current IP is not listed on that file, so I think it's fixed now
