### ISSUE TITLE
V3 Android Automatic Plugin Loading not documented

### ISSUE THREAD

**Issue by ultimate-tester** [ionic-team/capacitor-site#308]
Hello all,

I'm having trouble with several official plugins from Capacitor after upgrading to V3 on Android.
At first I thought it was a problem with the plugin itself, but I'm getting this error on a lot of plugins:

`Error: "Share" plugin is not implemented on android`

My MainActivity is completely empty as auto-generated by the npx cap init command but I have the feeling I'm missing something, therefore I believe something is missing in the documentation.

Is it indeed something documentation wise, or did I find a bug?

**Comment by elylucas** [comment]
did you figure it out?

**Comment by ultimate-tester** [comment]
Thanks for following up. Yup, just another stupid user (me) not running sync commands. I was purely relying on the copy command and expected that this was sufficient. All plugins started working after the sync command.

**Comment by elylucas** [comment]
Yep, bit me many times as well, and its good feedback, thanks!
