### ISSUE TITLE
After update this doesm'

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/capacitor-site#326]
https://capacitorjs.com/docs/web#using-capacitor-as-a-script-include

Because the plugins were taken away from```@capacitor/core``` we, users of Vanilla JavaScript don't have a way to use plugins anymore, at least in the way we did in V2.

Tried it with Filesystem.

**Comment by jcesarmobile** [comment]
For native you can use Capacitor.Plugins object, it still contains all plugins an you can use all the plugin methods, but for web you'll have to use a bundler.
