### ISSUE TITLE
Device plugin - uuid not available

### ISSUE THREAD

**Issue by migliori** [ionic-team/capacitor-site#354]
Hello,

I need to identify the users devices ; I call `Device.getInfo()` but it doesn't return any _info.uuid_
Instead I found the device name with __info.name__

Tested with iPhone and androïd phones connected to xcode and android studio.

I hope the device name is a reliable value?

**Comment by jcesarmobile** [comment]
The id information was moved to its own `getId` function

https://capacitorjs.com/docs/apis/device#getid

**Comment by migliori** [comment]
Thanks for your answer.

That's perfect, it may be an idea to update the documentation

**Comment by jcesarmobile** [comment]
What documentation are you referring to?

The link I provided is for the documentation and it has the getId and the getInfo doesn't include the uuid.

**Comment by migliori** [comment]
Your answer made me realize that I was on the old V2 documentation: https://capacitorjs.com/docs/v2/apis/device#deviceinfo
Google sadly led me there. My fault, everythinhg is perfect on your side.
