### ISSUE TITLE
npx cap serve has been removed.

### ISSUE THREAD

**Issue by MagedEWilliam** [ionic-team/capacitor-site#433]
Target: https://capacitorjs.com/docs/v2/web#developing-your-app
When running command ```npx cap serve``` an error is returned saying:
```
[error] The serve command has been removed.
        Use a third-party tool for serving single page apps, such as serve: https://www.npmjs.com/package/serve
```

**Comment by jcesarmobile** [comment]
Those are capacitor 2 docs, serve was removed in capacitor 3
