### ISSUE TITLE
Certificate Pinning

### ISSUE THREAD

**Issue by JumaBok** [ionic-team/capacitor-site#439]
Genuine question on this one - but is pinning not considered an obsolete / bad practice today? I'm by no means a security expert but it was my impression that this causes more issues than it solves, and has since been essentially abandoned. Just noticed this when reviewing your security documentation (as a form of basic checklist if anything)...

I may be wrong!

Some references I've reviewed:

https://www.digicert.com/blog/certificate-pinning-what-is-certificate-pinning
https://cheapsslsecurity.com/p/what-is-http-public-key-pinning-and-why-its-not-good/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

Maybe I'm getting confused with two different approaches.

Thanks

**Comment by jcesarmobile** [comment]
closing since latest docs don't mention anything about certificate pinning
