### ISSUE TITLE
CDN link PWA Elements is wrong - but is different from MD?

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/capacitor-site#446]
https://github.com/ionic-team/capacitor-site/edit/main/pages/docs/v3/web/pwa-elements.md

displays as:
```html
<script
  type="module"
  src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.jspwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"
></script>
<script
  nomodule
  src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.jspwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"
></script>
```
on https://capacitorjs.com/docs/web/pwa-elements - which is an incorrect and malfunctioning CDN reference.

whereas the markdown source seems to show the proper CDN reference:

![image](https://user-images.githubusercontent.com/16119174/178160766-80459eec-ef18-452a-bdb4-b47cdb873219.png)

So, it should show like below on https://capacitorjs.com/docs/web/pwa-elements  

```html
<script
  type="module"
  src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.esm.js"
></script>
<script
  nomodule
  src="https://unpkg.com/@ionic/pwa-elements@latest/dist/ionicpwaelements/ionicpwaelements.js"
></script>
```

**Comment by jcesarmobile** [comment]
It's working fine now
