### ISSUE TITLE
uuid as returned from getId() (v4) is different than getInfo() uuid (v2)

### ISSUE THREAD

**Issue by chrisvor** [ionic-team/capacitor-site#454]
In my app, I register the UUID of the user device in my database, so as to use it when sending push notifications (e.g. send to all user devices or to the one currently being used - identified by their UUID).

In Capacitor v2, I used to call getInfo() and use uuid from there which was in the format of "5c1b0ad1-34e1-xxxx-yyyy-zzzzzzzzzzzz".

I updated to v4 and now call the new getId() function, however the uuid returned is very different, like "3dba51xxxxxxxxxx".

Why are they different? (the above two examples were from the same device, on the same android version)

I could simply re-register the device on first (or every) run of the new version, but that would make the old uuid's replaced, and hence all previous data related to them would be orphaned. So I would need to introduce a 2nd uuid property and match either which makes the whole process unnecessarily complex.

Thank you

**Comment by jcesarmobile** [comment]
you can check that the code for both Android is basically still the same on Capacitor 2 and on version 4 of the plugins
https://github.com/ionic-team/capacitor/blob/b83aba71f6d297720fc0395347de0f48695d1153/android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java#L121
https://github.com/ionic-team/capacitor-plugins/blob/main/device/android/src/main/java/com/capacitorjs/plugins/device/Device.java#L54

What's the Android version of the device? On Android 8+ the value will change in different situations, like using a different machine to build the .apk (if it's a debug build), or if using different users on the same device.

https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

**Comment by chrisvor** [comment]
Hi and thanks for the response.
As I said, the app was developed using Capacitor 2 and has been upgraded to Capacitor 4.
Also I mentioned that "(the above two examples were from the same device, on the same android version)". What I meant was, the app in Capacitor v2 was installed on the device, it produced the first uuid (long) and then I installed the Capacitor v4 version (on the same device, same android version, same user, same app id) and the uuid changed to the short version, therefore suggesting that getId() does not produce the same uuid as the old getInfo() calls.

**Comment by jcesarmobile** [comment]
But has the device been updated from Android < 8 to Android >= 8 over time? What's the current Android version of the device?
The linked docs say that the value can persist with the old format even in Android >= 8 if the value was previously retrieved in Android < 8, but then if you uninstall and reinstall the app you'll get the new format.

**Comment by chrisvor** [comment]
Its an S22 Ultra on Android 12. always has been on android 12

**Comment by jcesarmobile** [comment]
I've tested in [this](https://github.com/jcesarmobile/capacitor-example-app) Capacitor 2 app and the uuid is also a 16 char string with no dashes on it, looks like you were getting the web uuid that has dashes on it instead of the native value.

**Comment by chrisvor** [comment]
I was using the Device.getInfo() method, how could it return the web uuid? 
Actually when I upgraded to Capacitor 4, I didnt notice the breaking change, and so the uuid property was missing and I had a compilation error. That's when I discovered that the getId() method was introduced. That's the only change I made.....

**Comment by jcesarmobile** [comment]
There are several things that can cause that the plugin uses the web version instead of the native version
this link is for Capacitor 3+
https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented

For Capacitor 2 the most common problem was using the plugins like this:

```
import { Device } from '@capacitor/core';
const info = await Device.getInfo();
```

Instead of how documented

```
import { Plugins } from '@capacitor/core';
const { Device } = Plugins;
const info = await Device.getInfo();
```

**Comment by chrisvor** [comment]
You are right, I was using 
import { Device } from '@capacitor/core';

I dont know why I was doing it that way, I'm using Geolocation as well, and that one I did the documented way.....
We live and learn I guess

Many thanks for your help, closing (non) issue :)
