### ISSUE TITLE
Bug: Right-side navigation links do not work as expected

### ISSUE THREAD

**Issue by dallastjames** [ionic-team/capacitor-site#46]
Browser: Vivaldi (Chromium-based)

The right-side quick nav for in-document navigation is not scrolling to the correct position in the document. Clicking on the links does in fact update the URL, but the document will be scrolled to the top, rather than scrolling to correct section.

![image](https://user-images.githubusercontent.com/16655763/86046886-3c761680-ba0b-11ea-8a64-e58d132f640b.png)

Directly navigating to a section works correctly (see this example link: https://capacitorjs.com/docs/guides/push-notifications-firebase#prerequisites ) but if you attempt to use the right-nav for any other links, it immediately jumps to the top.

**Comment by jaredcbaum** [comment]
Fixed in latest
