### ISSUE TITLE
Configuring Android section has wrong information

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor-site#60]
In example, changing the app ID shouldn't be done in the AndroidManifest.xml 
https://capacitorjs.com/docs/android/configuration#changing-app-id

The app ID is generated from `applicationId` field in App's `build.gradle`, so changes in `AndroidManifest.xml` result in value being restored after gradle sync.

**Comment by rdlabo** [comment]
I recreated the android folder when I did it before. If we are using Git, looking at differences isn't too difficult.

**Comment by jcesarmobile** [comment]
Not sure what that has to do with the issue I reported.
But users should never remove android folder and add it again. It can be easy to add the changes if you don’t have many, but if you did a lot of manual modifications you have to do all again.
