### ISSUE TITLE
bug: pull in GitHub data

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/capacitor-site#65]
The following data needs to be pulled in from GitHub on build. We can follow how we did this on the framework site. Right now this is hardcoded.

- GitHub stars (used on the landing page button in the header) https://capacitorjs.com/
  - Notice it says 4.1k, but it currently is at 4.2k
- Latest version (used on the docs page in the menu header) https://capacitorjs.com/docs
  - Notice it says 2.2.0 is the latest release, but it is actually 2.2.1: https://github.com/ionic-team/capacitor/releases

**Comment by jaredcbaum** [comment]
We currently aren't displaying the stars anymore.  Not sure where it used to say the version #, I think I might know where you mean and that space will be used for a version switcher.  Ok to close?
