### ISSUE TITLE
bug: features doesn't link to anything

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/capacitor-site#67]
From the landing page, click on the features in the top bar: https://capacitorjs.com/#features

Notice it doesn't move down at all. Ben would like it to link here:

<img width="1733" alt="Screen Shot 2020-07-13 at 5 46 16 PM" src="https://user-images.githubusercontent.com/6577830/87356811-c2787e00-c530-11ea-8741-2374ff29e2a0.png">

However, this might be kind of confusing imo since there is no actual word "Features" anywhere.

**Comment by jcesarmobile** [comment]
It works now, can probably be closed

**Comment by dwieeb** [comment]
It doesn't seem to work if the fragment `#features` is in the URL

**Comment by jaredcbaum** [comment]
Features nav item removed all together :+1:
