### ISSUE TITLE
bug: checked in merge conflicts

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/capacitor-site#69]
There are visible merge conflicts in this file, I noticed it in a recent PR when it showed up in a diff, but they were there prior to my PR as well.

https://github.com/ionic-team/capacitor-site/blob/e2fc19f56dd4795d089de865913d8e8e10310184/dist/hydrate/index.js#L8798

I don't know what issues this causes.

**Comment by brandyscarney** [comment]
Running `npm run build` fixes this but is this being run on vercel? Maybe this file shouldn't be checked in.

**Comment by jaredcbaum** [comment]
/dist folder is now included in .gitignore
