### ISSUE TITLE
feat: revisit code styles, see if there are alternatives

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/capacitor-site#71]
This is something Ben mentioned, get with him to decide on a new design

![image](https://user-images.githubusercontent.com/6577830/87471000-a2f25b80-c5eb-11ea-905e-bace92de85d2.png)

**Comment by jcesarmobile** [comment]
In capacitor 3 importing the plugin directly will be the recommended way, the Plugins object will still work. All examples should be updated.

**Comment by dwieeb** [comment]
I think this issue is related to text coloring, but yes I created another issue for updating the examples: https://github.com/ionic-team/capacitor-site/issues/96

**Comment by brandyscarney** [comment]
@dwieeb is correct, this issue is just about the text colors / syntax highlighting
