### ISSUE TITLE
 Wrong Documentation For Push Notification

### ISSUE THREAD

**Issue by mcroni** [ionic-team/capacitor-site#78]
In the docs, the documentation on the  `push-notification` page isn't correct. It shows contents of the `share`. I tried to reload the page with the `push notification` url  and it worked though. But using the `back` and `next` buttons don't show the actual content

**Comment by jcesarmobile** [comment]
You mean https://capacitorjs.com/docs/apis/push-notifications? 
It loads fine for me and buttons work fine too.
What browser are you testing in?

**Comment by mcroni** [comment]
Clicking on the link directly will send you the appropriate page, try moving to the `share` docs and use the next button to switch to that of `push notifications`. I'm using Brave Version 1.11.97

**Comment by jcesarmobile** [comment]
It works fine in Chrome, Firefox and Safari.

There has been a few reports of Brave having problems loading Push Notifications page (probably related to the name), so nothing we can fix other than changing the url, which I don't think we would do. 

https://github.com/ionic-team/capacitor/issues/1866
https://github.com/ionic-team/capacitor/issues/2790
https://github.com/ionic-team/capacitor/issues/2925

**Comment by rebron** [comment]
@mcroni Still an issue for you with Brave 1.13.82 our current release version? I couldn't reproduce on 1.13.82 and our current version in beta 1.14.x

**Comment by mcroni** [comment]
@rebron it works with  Brave 1.13.82
