### ISSUE TITLE
At certain breakpoint page does not shrink

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor-site#79]
Seems between large and medium viewport widths the content area does not shrink, causing the right column to be cut off (Firefox):

<img width="1074" alt="Screen Shot 2020-07-17 at 4 54 54 PM" src="https://user-images.githubusercontent.com/11214/87833806-607c8900-c84e-11ea-89dd-07789f56df03.png">

**Comment by dwieeb** [comment]
I believe this was fixed. (The right column still disappears at a certain point, though.)
