### ISSUE TITLE
Status bar color toggle is not working properly

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/capacitor-site#83]
status bar on ios is not working properly, observing exactly opposite results in terms of colors
when setStyle is light its turning dark and vice versa.
[Video demo](https://youtu.be/2_MDm7lAOTw), [code](https://github.com/pritamsoni-hsr/ionic-testing)

**Comment by dwieeb** [comment]
Pretty sure this is a bug report for Capacitor itself. If so, use the Capacitor repo: https://github.com/ionic-team/capacitor
